#!/bin/bash

output=/tmp/rundemo.debug

function run()
{
    echo "Switching to $1 Gbps"
    /usr/bin/python cmd_interpreter.py $2  >> $output 2>&1
    sleep 15
}

while [[ 1 ]]
do
    run "100" ikondemo100g.txt
    run "36"  ikondemo36g.txt
    run "6"   ikondemo1g.txt
    run "36"  ikondemo36g.txt
done
