#!/usr/bin/expect

set repo [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]

spawn git clone --quiet "$repo"
expect "Username for 'http://git.esss.dk':"
send "$username\r"
expect "Password for 'http://$username@git.esss.dk':"
send "$password\r"
expect eof
